### ISSUE TITLE
pypy on macos cannot run our tests

### ISSUE THREAD

**Issue by psarka** [harlowja/fasteners#60]
This is the stacktrace from github actions:

```
Thu, 26 Nov 2020 11:56:09 GMT Process PoolWorker-120:
Thu, 26 Nov 2020 11:56:09 GMT Traceback (most recent call last):
Thu, 26 Nov 2020 11:56:09 GMT   File "/Users/runner/hostedtoolcache/PyPy/2.7.13/x64/lib-python/2.7/multiprocessing/process.py", line 258, in _bootstrap
Thu, 26 Nov 2020 11:56:09 GMT     self.run()
Thu, 26 Nov 2020 11:56:09 GMT   File "/Users/runner/hostedtoolcache/PyPy/2.7.13/x64/lib-python/2.7/multiprocessing/process.py", line 114, in run
Thu, 26 Nov 2020 11:56:09 GMT     self._target(*self._args, **self._kwargs)
Thu, 26 Nov 2020 11:56:09 GMT   File "/Users/runner/hostedtoolcache/PyPy/2.7.13/x64/lib-python/2.7/multiprocessing/pool.py", line 102, in worker
Thu, 26 Nov 2020 11:56:09 GMT     task = get()
Thu, 26 Nov 2020 11:56:09 GMT   File "/Users/runner/hostedtoolcache/PyPy/2.7.13/x64/lib-python/2.7/multiprocessing/queues.py", line 378, in get
Thu, 26 Nov 2020 11:56:09 GMT     return recv()
Thu, 26 Nov 2020 11:56:09 GMT   File "/Users/runner/hostedtoolcache/PyPy/2.7.13/x64/lib-python/2.7/pickle.py", line 1439, in loads
Thu, 26 Nov 2020 11:56:09 GMT     return Unpickler(file).load()
Thu, 26 Nov 2020 11:56:09 GMT   File "/Users/runner/hostedtoolcache/PyPy/2.7.13/x64/lib-python/2.7/pickle.py", line 909, in load
Thu, 26 Nov 2020 11:56:09 GMT     dispatch[key](self)
Thu, 26 Nov 2020 11:56:09 GMT   File "/Users/runner/hostedtoolcache/PyPy/2.7.13/x64/lib-python/2.7/pickle.py", line 1268, in load_build
Thu, 26 Nov 2020 11:56:09 GMT     setstate(state)
Thu, 26 Nov 2020 11:56:09 GMT   File "/Users/runner/hostedtoolcache/PyPy/2.7.13/x64/site-packages/diskcache/persistent.py", line 324, in __setstate__
Thu, 26 Nov 2020 11:56:09 GMT     self.__init__(directory=state)
Thu, 26 Nov 2020 11:56:09 GMT   File "/Users/runner/hostedtoolcache/PyPy/2.7.13/x64/site-packages/diskcache/persistent.py", line 101, in __init__
Thu, 26 Nov 2020 11:56:09 GMT     self._cache = Cache(directory, eviction_policy='none')
Thu, 26 Nov 2020 11:56:09 GMT   File "/Users/runner/hostedtoolcache/PyPy/2.7.13/x64/site-packages/diskcache/core.py", line 509, in __init__
Thu, 26 Nov 2020 11:56:09 GMT     self.reset(key, value, update=False)
Thu, 26 Nov 2020 11:56:09 GMT   File "/Users/runner/hostedtoolcache/PyPy/2.7.13/x64/site-packages/diskcache/core.py", line 2462, in reset
Thu, 26 Nov 2020 11:56:09 GMT     (old_value,), = sql('PRAGMA %s' % (pragma)).fetchall()
Thu, 26 Nov 2020 11:56:09 GMT   File "/Users/runner/hostedtoolcache/PyPy/2.7.13/x64/lib_pypy/_sqlite3.py", line 401, in execute
Thu, 26 Nov 2020 11:56:09 GMT     return cur.execute(*args)
Thu, 26 Nov 2020 11:56:09 GMT   File "/Users/runner/hostedtoolcache/PyPy/2.7.13/x64/lib_pypy/_sqlite3.py", line 729, in wrapper
Thu, 26 Nov 2020 11:56:09 GMT     return func(self, *args, **kwargs)
Thu, 26 Nov 2020 11:56:09 GMT   File "/Users/runner/hostedtoolcache/PyPy/2.7.13/x64/lib_pypy/_sqlite3.py", line 896, in execute
Thu, 26 Nov 2020 11:56:09 GMT     return self.__execute(False, sql, [params])
Thu, 26 Nov 2020 11:56:09 GMT   File "/Users/runner/hostedtoolcache/PyPy/2.7.13/x64/lib_pypy/_sqlite3.py", line 824, in __execute
Thu, 26 Nov 2020 11:56:09 GMT     self.__statement = self.__connection._statement_cache.get(sql)
Thu, 26 Nov 2020 11:56:09 GMT   File "/Users/runner/hostedtoolcache/PyPy/2.7.13/x64/lib_pypy/_sqlite3.py", line 186, in get
Thu, 26 Nov 2020 11:56:09 GMT     stat = Statement(self.connection, sql)
Thu, 26 Nov 2020 11:56:09 GMT   File "/Users/runner/hostedtoolcache/PyPy/2.7.13/x64/lib_pypy/_sqlite3.py", line 1069, in __init__
Thu, 26 Nov 2020 11:56:09 GMT     raise self.__con._get_exception(ret)
Thu, 26 Nov 2020 11:56:09 GMT OperationalError: locking protocol
Thu, 26 Nov 2020 11:56:47 GMT Process PoolWorker-121:
Thu, 26 Nov 2020 11:56:47 GMT Traceback (most recent call last):
Thu, 26 Nov 2020 11:56:47 GMT   File "/Users/runner/hostedtoolcache/PyPy/2.7.13/x64/lib-python/2.7/multiprocessing/process.py", line 258, in _bootstrap
Thu, 26 Nov 2020 11:56:47 GMT     self.run()
Thu, 26 Nov 2020 11:56:47 GMT   File "/Users/runner/hostedtoolcache/PyPy/2.7.13/x64/lib-python/2.7/multiprocessing/process.py", line 114, in run
Thu, 26 Nov 2020 11:56:47 GMT     self._target(*self._args, **self._kwargs)
Thu, 26 Nov 2020 11:56:47 GMT   File "/Users/runner/hostedtoolcache/PyPy/2.7.13/x64/lib-python/2.7/multiprocessing/pool.py", line 102, in worker
Thu, 26 Nov 2020 11:56:47 GMT     task = get()
Thu, 26 Nov 2020 11:56:47 GMT   File "/Users/runner/hostedtoolcache/PyPy/2.7.13/x64/lib-python/2.7/multiprocessing/queues.py", line 378, in get
Thu, 26 Nov 2020 11:56:47 GMT     return recv()
Thu, 26 Nov 2020 11:56:47 GMT   File "/Users/runner/hostedtoolcache/PyPy/2.7.13/x64/lib-python/2.7/pickle.py", line 1439, in loads
Thu, 26 Nov 2020 11:56:47 GMT     return Unpickler(file).load()
Thu, 26 Nov 2020 11:56:47 GMT   File "/Users/runner/hostedtoolcache/PyPy/2.7.13/x64/lib-python/2.7/pickle.py", line 909, in load
Thu, 26 Nov 2020 11:56:47 GMT     dispatch[key](self)
Thu, 26 Nov 2020 11:56:47 GMT   File "/Users/runner/hostedtoolcache/PyPy/2.7.13/x64/lib-python/2.7/pickle.py", line 1268, in load_build
Thu, 26 Nov 2020 11:56:47 GMT     setstate(state)
Thu, 26 Nov 2020 11:56:47 GMT   File "/Users/runner/hostedtoolcache/PyPy/2.7.13/x64/site-packages/diskcache/persistent.py", line 324, in __setstate__
Thu, 26 Nov 2020 11:56:47 GMT     self.__init__(directory=state)
Thu, 26 Nov 2020 11:56:47 GMT   File "/Users/runner/hostedtoolcache/PyPy/2.7.13/x64/site-packages/diskcache/persistent.py", line 101, in __init__
Thu, 26 Nov 2020 11:56:47 GMT     self._cache = Cache(directory, eviction_policy='none')
Thu, 26 Nov 2020 11:56:47 GMT   File "/Users/runner/hostedtoolcache/PyPy/2.7.13/x64/site-packages/diskcache/core.py", line 509, in __init__
Thu, 26 Nov 2020 11:56:47 GMT     self.reset(key, value, update=False)
Thu, 26 Nov 2020 11:56:47 GMT   File "/Users/runner/hostedtoolcache/PyPy/2.7.13/x64/site-packages/diskcache/core.py", line 2462, in reset
Thu, 26 Nov 2020 11:56:47 GMT     (old_value,), = sql('PRAGMA %s' % (pragma)).fetchall()
Thu, 26 Nov 2020 11:56:47 GMT   File "/Users/runner/hostedtoolcache/PyPy/2.7.13/x64/lib_pypy/_sqlite3.py", line 401, in execute
Thu, 26 Nov 2020 11:56:47 GMT     return cur.execute(*args)
Thu, 26 Nov 2020 11:56:47 GMT   File "/Users/runner/hostedtoolcache/PyPy/2.7.13/x64/lib_pypy/_sqlite3.py", line 729, in wrapper
Thu, 26 Nov 2020 11:56:47 GMT     return func(self, *args, **kwargs)
Thu, 26 Nov 2020 11:56:47 GMT   File "/Users/runner/hostedtoolcache/PyPy/2.7.13/x64/lib_pypy/_sqlite3.py", line 896, in execute
Thu, 26 Nov 2020 11:56:47 GMT     return self.__execute(False, sql, [params])
Thu, 26 Nov 2020 11:56:47 GMT   File "/Users/runner/hostedtoolcache/PyPy/2.7.13/x64/lib_pypy/_sqlite3.py", line 824, in __execute
Thu, 26 Nov 2020 11:56:47 GMT     self.__statement = self.__connection._statement_cache.get(sql)
Thu, 26 Nov 2020 11:56:47 GMT   File "/Users/runner/hostedtoolcache/PyPy/2.7.13/x64/lib_pypy/_sqlite3.py", line 186, in get
Thu, 26 Nov 2020 11:56:47 GMT     stat = Statement(self.connection, sql)
Thu, 26 Nov 2020 11:56:47 GMT   File "/Users/runner/hostedtoolcache/PyPy/2.7.13/x64/lib_pypy/_sqlite3.py", line 1069, in __init__
Thu, 26 Nov 2020 11:56:47 GMT     raise self.__con._get_exception(ret)
Thu, 26 Nov 2020 11:56:47 GMT OperationalError: locking protocol
```

**Comment by psarka** [comment]
Apparently now they can, so this resolved itself.
